#!/usr/bin/env bash
# To displays the time for 12 hours & 59 minutes.
Hour=0
while [ $hour <= 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute <= 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
